-- DataOps SWAT Team — example fix (generated by EngineerAgent)
-- Fix ID:     fix-inc-freshness_violation-0b17067135fb-99b54230
-- Incident:   inc-freshness_violation-0b17067135fb
-- Target:     urn:li:dataset:(urn:li:dataPlatform:dbt,b2fd91.ORDER_ENTRY_DB.analytics.order_details,PROD)
-- Fix type:   FRESHNESS_RERUN
-- Explanation:Rerun the ingestion for order_details and verify the latest order_date value.

-- FRESHNESS_RERUN: refresh order_details and confirm recent data
SELECT MAX(order_date) AS latest_ingested_ts FROM order_details;
